using SS14LocalMods.Conversations;
using Content.Client.UserInterface.Systems.Chat.Widgets;
using Robust.Client.UserInterface.Controls;

var checks = 0;
void Check(bool condition, string title) { if (!condition) throw new Exception(title); checks++; }
void Parse(string channel, string display, string text, string? name, string? radio)
{
    var speaker = ConversationFilter.Parse(channel, display, text);
    Check(speaker.Name == name && speaker.RadioChannel == radio, $"Metadata: {display}");
}
Parse("Local", "[BubbleHeader][bold][Name][color=#8BC9DAFF]Эмили Волкова[/color][/Name][/bold][/BubbleHeader] говорит, \"Да\"", "Да", "Эмили Волкова", null);
Parse("Whisper", "[italic][Name]Феликс Вульпати[/Name] шепчет,\"Привет\"[/italic]", "Привет", "Феликс Вульпати", null);
Parse("Radio", "[color=#FF4242FF]\\[Безопасность\\] [bold][color=#323BA9FF]\\[адвокат\\] Феликс Вульпати[/color][/bold] говорит, \"Привет\"[/color]", "Привет", "Феликс Вульпати", "Безопасность");
Parse("Radio", "[color=#FF733CFF]\\[Инженерный\\] [bold][textlink=\"x\" entity=\"42\"]Нина Петрова[/textlink][/bold] докладывает, \"Готово\"[/color]", "Готово", "Нина Петрова", "Инженерный");
Parse("Radio", "[font size=14][bold]Объявление Станции:[/font][font size=12] Прибыл экипаж[/bold][/font]", "Прибыл экипаж", "Объявление Станции", null);
Parse("Emote", "[italic]Тах-Риит хихикает![/italic]", "хихикает!", "Тах-Риит", null);
Parse("OOC", "[Name]Example[/Name]: hi", "hi", "Example", null);
Parse("OOC", "OOC: [bold]Player:[/bold] hi", "hi", "Player", null);
Parse("OOC", "OOC: [bold][color=#ABCDEF]Patron[/color]:[/bold] hi", "hi", "Patron", null);
Parse("LOOC", "LOOC: [bold]Нина:[/bold] привет", "привет", "Нина", null);
Parse("Dead", "DEAD: [bold][BubbleHeader]Ghost[/BubbleHeader]:[/bold] [BubbleContent]hi[/BubbleContent]", "hi", "Ghost", null);
Parse("Admin", "ADMIN: [bold]Staff:[/bold] hi", "hi", "Staff", null);
Parse("Admin", "[bold]ADMIN: Notice[/bold]", "Notice", null, null);
Parse("Server", "Welcome", "Welcome", null, null);
Parse("Local", "[Name]\\[Имя\\][/Name] говорит", "говорит", "[Имя]", null);
Parse("Radio", "[color=red]\\[Medical\\] no supported name[/color]", "hi", null, "Medical");
Parse("Radio", "[color=red]\\[Security\\] [bold]Sam[/bold] says, \"\\[Medical\\] Alex\"", "[Medical] Alex", "Sam", "Security");
var sam = new Speaker("Сэм", "Безопасность");
var nina = new Speaker("Нина", "Инженерный");
var unknown = new Speaker(null, null);
var filter = new ConversationFilter();
Check(!filter.Active && filter.Matches(unknown), "No filters keeps system messages");
filter.Query = "  сЭм  ";
Check(filter.Matches(sam) && !filter.Matches(nina) && !filter.Matches(unknown), "Case-insensitive name-only search");
filter.Query = ""; filter.SelectedOnly = true;
Check(!filter.Matches(sam) && !filter.Matches(unknown), "Explicit empty selection matches nobody");
filter.Selected.Add(sam.Key!); filter.Selected.Add(nina.Key!);
Check(filter.Matches(sam) && filter.Matches(nina), "Multiple speakers use OR");
Check(filter.Matches(new Speaker("сЭм", null)), "Same voice across local and radio");
filter.RadioChannel = "безопасность";
Check(filter.Matches(sam) && !filter.Matches(nina) && !filter.Matches(new Speaker("Сэм", null)), "Department is radio channel, combined using AND");
filter.Query = "Нина";
Check(!filter.Matches(sam) && !filter.Matches(nina), "Combined name and department");
filter.Reset();
Check(!filter.Active && filter.Selected.Count == 0 && filter.Matches(unknown), "Reset restores everything");
filter.RadioChannel = "Unknown fork channel";
Check(filter.Matches(new Speaker("Name", "Unknown fork channel")), "Channels are discovered, not hardcoded");
filter.Reset(); filter.MessageQuery = "  зОмБи  ";
Check(filter.Active && filter.Matches(sam, "Там ЗОМБИ!"), "Message word search ignores case and surrounding spaces");
Check(!filter.Matches(new Speaker("Зомби", null), "Привет"), "Speaker name is not message text");
Check(filter.Matches(unknown, "зомби!"), "Unknown speakers can still match message text");
filter.MessageQuery = "в медбее";
Check(filter.Matches(sam, "Зомби в медбее!") && !filter.Matches(sam, "Зомби в баре!"), "Phrase search");
filter.Query = "Нина";
Check(!filter.Matches(sam, "Зомби в медбее!"), "Name and message searches combine with AND");
filter.Reset();
Check(!filter.Active && filter.MessageQuery == "" && filter.Matches(sam, "Привет"), "Reset clears text search");
var time = ConversationFilter.GameTime(160, 100, TimeSpan.FromSeconds(10), TimeSpan.FromSeconds(1));
Check(time == TimeSpan.FromSeconds(70) && ConversationFilter.FormatTime(time) == "00:01:10", "History tick timestamp");
Check(ConversationFilter.GameTime(90, 100, TimeSpan.FromSeconds(20), TimeSpan.FromSeconds(1)) == TimeSpan.FromSeconds(10), "Historical tick before timebase");
Check(ConversationFilter.GameTime(0, 100, TimeSpan.Zero, TimeSpan.FromSeconds(1)) == null, "Invalid negative time");
Check(ConversationFilter.GameTime(1, 0, TimeSpan.Zero, TimeSpan.Zero) == null, "Missing tick rate");
Check(ConversationFilter.GameTime(uint.MaxValue, 0, TimeSpan.MaxValue, TimeSpan.MaxValue) == null, "Clock overflow");
Check(ConversationFilter.FormatTime(TimeSpan.FromHours(25) + TimeSpan.FromSeconds(9)) == "25:00:09", "Hours never wrap at midnight");
Check(ConversationFilter.FormatTime(null) == "—", "Unknown time isn't invented");

// Exercise actual Harmony hooks, events and repopulation against a minimal game API fixture.
SS14LocalMods.Mod.Install(typeof(ChatBox).Assembly);
var chat = new ChatBox();
var root = chat.Layout.Children.OfType<BoxContainer>().First();
var toolbar = (BoxContainer)root.Children[0];
var panel = (BoxContainer)root.Children[1];
var expand = (Button)toolbar.Children[0];
var timeButton = (Button)toolbar.Children[2];
var queryRow = (BoxContainer)panel.Children[0];
var search = (LineEdit)queryRow.Children[0];
var department = (OptionButton)queryRow.Children[1];
var textSearch = (LineEdit)panel.Children[1];
var selection = (BoxContainer)panel.Children[2];
var only = (Button)selection.Children[0];
var reset = (Button)selection.Children[1];
var people = (BoxContainer)panel.Children[3].Children[0];
var a = new ChatMessage("Radio", "A", "\\[Security\\] [bold]Sam[/bold] says A");
var b = new ChatMessage("Local", "B", "[Name]Nina[/Name] says B");
chat.Receive(a, 160); chat.Receive(b, 161);
Check(chat.Contents.Lines.Count == 2 && chat.Contents.Lines[0].Contains("00:01:10"), "Timestamp inserted by AddLine hook");
Check(a.WrappedMessage == "\\[Security\\] [bold]Sam[/bold] says A", "Original markup is never mutated");
expand.Click();
Check(panel.Visible && people.Children.Count == 2, "Expand lists discovered voices");
people.Children.OfType<Button>().Single(x => x.Text == "Sam").Click();
Check(only.Pressed && chat.Contents.Lines.Count == 1 && chat.Contents.Lines[0].Contains("says A"), "Selecting a voice immediately filters existing history");
people.Children.OfType<Button>().Single(x => x.Text == "Nina").Click();
Check(chat.Contents.Lines.Count == 2, "Selecting two voices shows both");
search.Edit("Nina");
Check(chat.Contents.Lines.Count == 1 && chat.Contents.Lines[0].Contains("says B"), "Search filters history by name");
reset.Click(); department.Choose(1);
Check(chat.Contents.Lines.Count == 1 && department.SelectedId == 1, "Department popup selects and filters");
chat.RadioEnabled = false; chat.Repopulate();
Check(chat.Contents.Lines.Count == 0, "Native channel filters still apply");
chat.RadioEnabled = true; reset.Click();
Check(chat.Contents.Lines.Count == 2 && people.Children.Count == 2, "Reset restores history and checklist");
timeButton.Click();
Check(chat.Contents.Lines[0] == a.WrappedMessage, "Timestamp toggle removes prefix");
var other = new ChatBox(); other.Receive(a, 160);
Check(other.Contents.Lines.Count == 1 && other.Contents.Lines[0].Contains("00:01:10"), "Separate chat views have independent filters");
chat.Receive(new ChatMessage("Local", "ЗОМБИ! в медбее", "[Name]Nina[/Name] says ЗОМБИ! в медбее"), 162);
textSearch.Edit("зомби");
Check(chat.Contents.Lines.Count == 1 && chat.Contents.Lines[0].Contains("[Name]Nina[/Name]"), "Text search returns original speaker and message");
chat.Receive(new ChatMessage("Local", "Нет опасности", "[Name]Sam[/Name] says Нет опасности"), 163);
Check(chat.Contents.Lines.Count == 1, "Live nonmatching message stays hidden");
chat.Receive(new ChatMessage("Radio", "Зомби в баре", "\\[Security\\] [bold]Sam[/bold] says Зомби в баре"), 164);
Check(chat.Contents.Lines.Count == 2, "Live matching messages appear");
search.Edit("Sam");
Check(chat.Contents.Lines.Count == 1 && chat.Contents.Lines[0].Contains("Зомби в баре"), "UI combines name and message filters");
reset.Click();
Check(textSearch.Text == "" && chat.Contents.Lines.Count == 5, "UI reset restores all messages and clears text field");
chat.ThrowNext = true;
try { chat.Receive(new ChatMessage("Local", "C", "[Name]Sam[/Name] says C"), 162); } catch (InvalidOperationException) { }
chat.AddLine("Direct status", "white");
Check(chat.Contents.Lines[^1] == "Direct status", "Finalizer clears pending timestamp after native exception");
Console.WriteLine($"Conversations: {checks} checks passed (metadata, filters, clock and Harmony integration).");
